{{- if .Values.tls.enabled }}
{{- if .Values.tls.generateCerts }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "voice-ferry.tlsSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voice-ferry.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-1"
type: kubernetes.io/tls
data:
  tls.crt: {{ include "voice-ferry.tlsCert" . | b64enc }}
  tls.key: {{ include "voice-ferry.tlsKey" . | b64enc }}
{{- end }}
{{- end }}

{{/*
Generate a self-signed certificate for Voice Ferry
*/}}
{{- define "voice-ferry.tlsCert" }}
-----BEGIN CERTIFICATE-----
MIIDXTCCAkWgAwIBAgIJAKL0UG+9dKMLMA0GCSqGSIb3DQEBCwUAMEUxCzAJBgNV
BAYTAkFVMRMwEQYDVQQIDApTb21lLVN0YXRlMSEwHwYDVQQKDBhJbnRlcm5ldCBX
aWRnaXRzIFB0eSBMdGQwHhcNMjUwNTI5MDAwMDAwWhcNMjYwNTI5MDAwMDAwWjBF
MQswCQYDVQQGEwJBVTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50
ZXJuZXQgV2lkZ2l0cyBQdHkgTHRkMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIB
CgKCAQEAyVkqtLqOPW2MBFwgEd8BVyZhjvZ5VL3n2Jz1QqNBcOwF3ZJgC7MeEgC3
2sQPLx8GXKR8lP2KnWu5Jn4yGlzCJoH7FJjYKFD2Lj8sGyEfK2uYZXJpJSEqSYP8
=
-----END CERTIFICATE-----
{{- end }}

{{/*
Generate a private key for Voice Ferry
*/}}
{{- define "voice-ferry.tlsKey" }}
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDJWSq0uo49bYwE
XCAR3wFXJmGO9nlUvefYnPVCo0Fw7AXdkmALsx4SALfaxA8vHwZcpHyU/Yqda7km
fjIaXMImgfsUmNgoUPYuPywbIR8ra5hlcmklISpJg/w=
-----END PRIVATE KEY-----
{{- end }}
