apiVersion: v1
kind: Service
metadata:
  name: {{ include "voice-ferry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "voice-ferry.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.sip.port }}
    targetPort: sip-udp
    protocol: UDP
    name: sip-udp
    {{- if and (eq .Values.service.type "NodePort") .Values.service.sip.nodePort }}
    nodePort: {{ .Values.service.sip.nodePort }}
    {{- end }}
  {{- if .Values.voiceFerry.sip.tls.enabled }}
  - port: {{ .Values.service.sipTls.port }}
    targetPort: sip-tls
    protocol: TCP
    name: sip-tls
    {{- if and (eq .Values.service.type "NodePort") .Values.service.sipTls.nodePort }}
    nodePort: {{ .Values.service.sipTls.nodePort }}
    {{- end }}
  {{- end }}
  - port: {{ .Values.service.grpc.port }}
    targetPort: grpc
    protocol: TCP
    name: grpc
    {{- if and (eq .Values.service.type "NodePort") .Values.service.grpc.nodePort }}
    nodePort: {{ .Values.service.grpc.nodePort }}
    {{- end }}
  - port: {{ .Values.service.health.port }}
    targetPort: health
    protocol: TCP
    name: health
    {{- if and (eq .Values.service.type "NodePort") .Values.service.health.nodePort }}
    nodePort: {{ .Values.service.health.nodePort }}
    {{- end }}
  selector:
    {{- include "voice-ferry.selectorLabels" . | nindent 4 }}
