# golangci-lint configuration file

run:
  timeout: 10m

output:
  print-issued-lines: true
  print-linter-name: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt

issues:
  exclude-rules:
    - path: ".*\\.pb\\.go$"
      linters:
        - all
    - path: ".*_generated\\.go$"
      linters:
        - all
    - path: "_test\\.go$"
      linters:
        - errcheck
