# Prometheus Configuration for Voice Ferry Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'voice-ferry-production'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Voice Ferry B2BUA metrics
  - job_name: 'voice-ferry-b2bua'
    static_configs:
      - targets: ['voice-ferry:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    scheme: http
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'voice-ferry-b2bua'

  # Redis metrics (if redis_exporter is deployed)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # etcd metrics
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    scrape_interval: 30s
    metrics_path: /metrics

  # RTPEngine metrics (if available)
  - job_name: 'rtpengine'
    static_configs:
      - targets: ['rtpengine:9235']
    scrape_interval: 30s
    scheme: http

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

# Storage configuration
storage:
  tsdb:
    retention.time: 15d
    retention.size: 10GB
    path: /prometheus/data

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://your-remote-storage/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"
