version: '3.8'

services:
  # Voice Ferry Web UI - connects to existing B2BUA infrastructure
  voice-ferry-web-ui:
    build: .
    container_name: voice-ferry-web-ui
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET:-voice-ferry-secret-key-change-in-production}
      - REDIS_URL=redis://sip-b2bua-redis:6379
      - ETCD_ENDPOINTS=http://sip-b2bua-etcd:2379
      - GRPC_ENDPOINT=sip-b2bua:50051
      - LOG_LEVEL=info
      - RATE_LIMIT_MAX=100
      - RATE_LIMIT_WINDOW=15
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
    networks:
      - go-voice-ferrycopy_b2bua-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  go-voice-ferrycopy_b2bua-network:
    external: true
