# Prometheus configuration for SIP B2BUA monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'sip-b2bua-monitor'

rule_files:
  # Add alerting rules here if needed
  # - "rules/*.yml"

scrape_configs:
  # SIP B2BUA metrics
  - job_name: 'sip-b2bua'
    static_configs:
      - targets: ['b2bua:9090']
    scrape_interval: 10s
    metrics_path: /metrics
    scheme: http
    
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    
  # Redis metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  # etcd metrics
  - job_name: 'etcd'
    static_configs:
      - targets: ['etcd:2379']
    scrape_interval: 30s
    metrics_path: /metrics
    
  # Node exporter (if available)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # Add alertmanager targets here if needed
          # - alertmanager:9093